---
- name: Include RedHat setup for CRI-O
  include_tasks: setup-redhat.yml
  when: ansible_os_family == "RedHat"

- name: Include Debian setup for CRI-O
  include_tasks: setup-debian.yml
  when: ansible_os_family == "Debian"
