- name: Add Kubernetes GPG key
  ansible.builtin.apt_key:
    url: "{{ kubernetes_gpg_key_Debian_url }}"
    state: present
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  when: ansible_os_family == "Debian"

- name: Add Kubernetes repository
  ansible.builtin.apt_repository:
    repo: "{{ kubernetes_repo_debian }}"
    state: present
    filename: kubernetes.list
  when: ansible_os_family == "Debian"

- name: Add Kubernetes GPG key (RedHat)
  ansible.builtin.rpm_key:
    key: "{{ kubernetes_gpg_key_RedHat_url }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: Add Kubernetes repository (RedHat)
  ansible.builtin.yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: "{{ kubernetes_repo_redhat }}"
    gpgcheck: yes
    gpgkey: "{{ kubernetes_gpg_key_RedHat_url }}"
    enabled: yes
    exclude: kubelet kubeadm kubectl cri-tools kubernetes-cni
  when: ansible_os_family == "RedHat"

- name: Install Kubernetes components (Debian)
  ansible.builtin.package:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
  when: ansible_os_family == "Debian"    

- name: Install Kubernetes components (RedHat)
  ansible.builtin.yum:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    disable_excludes: kubernetes
  when: ansible_os_family == "RedHat"


- name: Hold Kubernetes components (Debian)
  ansible.builtin.command:
    cmd: apt-mark hold kubelet kubeadm kubectl
  when: ansible_os_family == "Debian"
