---
- name: Get join command from master
  ansible.builtin.set_fact:
    join_command: "{{ hostvars['master-node']['join_command'] }}"

- name: Join the Kubernetes cluster
  ansible.builtin.command: "{{ join_command }}"
  become: yes
