- name: Update and upgrade APT packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
  when: ansible_os_family == "Debian"

- name: Update and upgrade YUM packages
  ansible.builtin.yum:
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"

- name: Disable swap
  ansible.builtin.command: swapoff -a

- name: Disable swap permanently
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^\s*(.*\s+swap\s+.*)$'
    replace: '#\1'

- name: Load kernel modules
  ansible.builtin.copy:
    dest: /etc/modules-load.d/containerd.conf
    content: |
      overlay
      br_netfilter

- name: Load overlay module
  ansible.builtin.modprobe:
    name: overlay

- name: Load br_netfilter module
  ansible.builtin.modprobe:
    name: br_netfilter

- name: Set kernel parameters for Kubernetes
  ansible.builtin.copy:
    dest: /etc/sysctl.d/kubernetes.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1

- name: Apply sysctl parameters
  ansible.builtin.command: sysctl --system

- name: Disable SELinux enforcement
  ansible.builtin.command:
    cmd: setenforce 0
  when: ansible_os_family == "RedHat"
  become: yes

- name: Set SELinux to permissive mode permanently
  ansible.builtin.replace:
     path: /etc/selinux/config
     regexp: '^SELINUX=enforcing$'
     replace: 'SELINUX=permissive'
  when: ansible_os_family == "RedHat"
  become: yes