---
- name: Gather Master Node IP
  command: hostname -I
  register: master_ip_raw

- name: Set Master Node IP
  set_fact:
    master_ip: "{{ master_ip_raw.stdout.split(' ')[0] }}"  

- name: Initialize Kubernetes cluster
  ansible.builtin.command: sudo kubeadm init --pod-network-cidr={{ pod_network_cidr }} --apiserver-advertise-address={{ master_ip }}
  register: kubeadm_init


- name: Create .kube directory
  ansible.builtin.file:
    path: /home/ubuntu/.kube
    state: directory
    mode: 0755
    owner: ubuntu
    group: ubuntu

- name: Copy admin.conf to user's kube config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: yes
    owner: ubuntu

- name: Install Calico network plugin
  ansible.builtin.command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/calico.yaml
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config

- name: Generate join command
  ansible.builtin.command: sudo kubeadm token create --print-join-command
  register: join_command
  run_once: true

- name: Set join command fact
  ansible.builtin.set_fact:
    join_command: "{{ join_command.stdout }}"
  run_once: true
